# Generated by Django 6.0.1 on 2026-01-23 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)]),
            preserve_default=False,
        ),
    ]
